---
- name: restart rsyslogd
  service: name=rsyslogd state=restarted
  sudo: yes
  failed_when: False
  when: not (is_integration_test is defined and is_integration_test and
      (ansible_os_family == "RedHat" or ansible_distribution == "CentOS"))
